function [] = call_NTM(matdir,filename_in,alpha_in,F_edge_0_in,beta_in,...
                        gamma_in,delta_in,epsilon_in,lambda_in,up_in_0,up_in_L,...
                        rel_in_0,rel_in_L,init_rescale,frac,axon_div)

%matdir=[cd filesep 'MatFiles'];

[N, M, Reg_edge_mass] = network_transport_model_Neu_func(matdir, ...
                                          'alpha',alpha_in,...
                                          'F_edge_0',F_edge_0_in,...
                                          'beta',beta_in,...
                                          'gamma1',gamma_in,...
                                          'delta',delta_in,...
                                          'epsilon',epsilon_in,...
                                          'lambda1',lambda_in,...
                                          'mu_r_0',rel_in_0,...
                                          'mu_r_L',rel_in_L,...
                                          'mu_u_0',up_in_0,...
                                          'mu_u_L',up_in_L,...
                                          'init_rescale',init_rescale,...
                                          'frac',frac,...
                                          'axon_div',axon_div);

save(filename_in,"N","M","Reg_edge_mass");