function [] = call_NTM2(matdir,filename_in,study_in,alpha_in,gamma_in,delta_in,epsilon_in,uprel_in)

F_edge_0_in = 0;
beta_in = 0.000001;
lambda_in = 0.025;
init_rescale = 0.02;
frac = 0.7;
axon_div = 'half';
%conn_subset = 'all';
conn_subset='Hippocampus+PC+RSP';

[N, M, ~] = network_transport_model_Neu_func(matdir, ...
                                          'alpha',alpha_in,...
                                          'F_edge_0',F_edge_0_in,...
                                          'beta',beta_in,...
                                          'gamma1',gamma_in,...
                                          'delta',delta_in,...
                                          'epsilon',epsilon_in,...
                                          'lambda1',lambda_in,...
                                          'mu_r_0',uprel_in,...
                                          'mu_r_L',uprel_in,...
                                          'mu_u_0',uprel_in,...
                                          'mu_u_L',uprel_in,...
                                          'init_rescale',init_rescale,...
                                          'frac',frac,...
                                          'axon_div',axon_div,...
                                          'connectome_subset',conn_subset,...
                                          'study',study_in,...
                                          'resmesh', 'coarse');

save(filename_in,"N","M","alpha_in","gamma_in","delta_in","epsilon_in","uprel_in");